# Generated by Django 4.0.5 on 2022-06-30 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('author', models.CharField(blank=True, max_length=250, null=True, verbose_name='author')),
                ('photo_book', models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='photo')),
                ('photo_author', models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='photo by aothor')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='pages')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='price')),
                ('retal_price_day', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='retal_price_day')),
                ('retal_period', models.IntegerField(blank=True, null=True, verbose_name='retal_period')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('status', models.CharField(choices=[('available', 'available'), ('rented', 'rented'), ('soled', 'soled')], max_length=50, verbose_name='status')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lms_app.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Book',
            },
        ),
    ]
